### ISSUE TITLE
Difficulties to use databases running BLAST

### ISSUE THREAD

**Issue by JavierUrban** [JavierUrban/Genome-assembly-of-the-copepod-Leptodiaptomus#3]
Do you need to create databases or is there a better option?

I created a database for copepods:

```
makeblastdb -in ../blastpacope/genomas_copepods/ncbi_dataset/data/db_all_copepods.fna -dbtype nucl -parse_seqids -out my_refrence2.fa
```
But they weigh a lot and running the BLAST is very slow.

To run BLAST use: 

```
blastn -db my_refrence2.fa -query ../blastpacope/minion/minion_carmen.fa -out results_allgenomes_tab.out -outfmt "6 sframe qseqid sseqid evalue pident mismatch" 
```
The function `-outfmt "6 <options>"` shows results in a tab separated table.  And although it's hard to see, the line of identity percentage in general it looks higher than 80%, so I think that maybe it is not so contaminated, however, I think it makes a BLAST with many databases it will take longer and be more difficult, so I would like to know if anyone knows a more easier way to run BLAST?

<img width="587" alt="results_blast" src="https://user-images.githubusercontent.com/59941891/97955698-6b5f1900-1d6c-11eb-9e64-d33db3717250.png">

Or if it will be a better option to start testing assemblers with different parameters? 
The first draft I have seems to be fragmented

<img width="1058" alt="busco_quast" src="https://user-images.githubusercontent.com/59941891/97956356-0c020880-1d6e-11eb-97c7-52f2547ca614.png">

**Comment by ghost** [comment]
We've already checked whether **blastn** is working properly.  Long runtimes seems to be more related to strategy itself, so the issue is likely heading towards a software/strategy alternative, treating reads concatenation as a metagenome.

**Comment by valeriafloral** [comment]
You can try using aligners for big sequence data such [DIAMOND](http://www.diamondsearch.org/index.php) or [LAST](http://last.cbrc.jp).

For more information on working with long-reads:

**Huson, D. H., Albrecht, B., Bağcı, C., Bessarab, I., Gorska, A., Jolic, D., & Williams, R. B.** (2018). MEGAN-LR: new algorithms allow accurate binning and easy interactive exploration of metagenomic long reads and contigs. Biology direct, 13(1), 6. 

**Bağcı, C., Beier, S., Górska, A., & Huson, D. H.** (2019). Introduction to the analysis of environmental sequences: metagenomics with MEGAN. In Evolutionary Genomics (pp. 591-604). Humana, New York, NY.

**Comment by ghost** [comment]
Try Alignment-free methods:
https://genomebiology.biomedcentral.com/track/pdf/10.1186/s13059-017-1319-7 <- Tables 1 & 2
https://sourceforge.net/projects/rafts3/ <- Fast Blast alternative

**Comment by valeriafloral** [comment]
For a review on how using metagenomic tools and construct metagenome-assembled genomes (MAGs):  
**Chen, L. X., Anantharaman, K., Shaiber, A., Eren, A. M., & Banfield, J. F.** (2020). Accurate and complete genomes from metagenomes. Genome research, 30(3), 315-333.

**Comment by solnavss** [comment]
Also you can give a look to this article:
Benchmarking the Minion: evaluating long reads for microbial profiling
DOI: 10.1038/s41598-020-61989-x

**Comment by valeriafloral** [comment]
In this blog the author documents the steps he follows to _Remove Microbial Contamination in Reads_ (bacteria, viral, fungi, protozoa, and archaea) in either short and long reads. He explains that for PacBio long reads, he didn’t find any tools specialized for that, so he tries several tools and concludes that minimap2 best met his needs.

https://yiweiniu.github.io/blog/2018/07/Remove-Contamination-of-Pokaryotic-Organisms-in-Reads/#more

Hope this could be useful.

**Comment by JavierUrban** [comment]
It was concluded that the blast is very slow due to the large number of reads of my data. Unfortunately from my local computer I can't do it any faster. But my colleagues suggested different alternatives: **(1)** use alignments with reference genomes and extract the reads of interest, **(2)** treat the samples as metagenomes to identify the sequences of microorganisms and **(3)** extract the sequences of mitochondria to assemble and compare them with other species.

Due to the computational resources that I have now, I decided to focus on alternatives 1 and 3, in the first one I will probably lose coverage for assembly de novo but I hope to complete later with more sequences. And in the third I had not thought, but it will help me answer some of my biological questions and due to the amount of data (sequences), I can work better for now.
